### ISSUE TITLE
pandapower 1.6

### ISSUE THREAD

**Issue by lthurner** [e2nIEE/pandapower#153]
A lot has changed since the last release, so I suggest releasing pandapower 1.6 soon. What do we still want to include in this release? I suggest:

- [x] runpp arguments: #122
- [x] ideal phase shifter with constant dU: #117 / #126 
- [x] runpp initialization: #113
- [x] clarify json IO issue #154 
- [x] power flow for networks without branches #157 
- [x] slacks and generators at one bus: #134
- [x] plotly version update #147 
- [ ] Update changelog
- [x] Update documentation

Will be included in future release:
- multigraph refactoring #85 / #127
- Iwamoto factor for PV buses #114

**Comment by lthurner** [comment]
@SteffenMeinecke: I think we had the "the transformer parameter has changed" warning for the adopted standard type parameters now for a long enough time that it can be deprecated, can you please do that?

**Comment by SteffenMeinecke** [comment]
> 
> 
> @SteffenMeinecke: I think we had the "the transformer parameter has changed" warning for the adopted standard type parameters now for a long enough time that it can be deprecated in 1.6, can you please do that?

Yes, I thought about that, too. I agree.

**Comment by lthurner** [comment]
released
